apiVersion: v2
name: coffeequeue
description: CoffeeQueue application and Postgres dependencies
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: Thotogelo
    url: https://github.com/thotogelo
icon: https://raw.githubusercontent.com/thotogelo/coffeequeue/main/src/main/resources/static/images/coffee-logo.png
keywords:
  - coffee
  - queue
  - spring boot
  - postgres
  - kubernetes
  - helm
  - docker