# postgres-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
        - name: postgres-data
          emptyDir: {} # for dev/testing, use PVC in prod
        - name: db-init-script
          configMap:
            name: db-init-script
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_DB
              value: coffeequeue
            - name: POSTGRES_PASSWORD
              value: postgres
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: db-init-script
              mountPath: /docker-entrypoint-initdb.d

#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: title
#  labels:
#    app: title
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: title
#  template:
#    metadata:
#      name: title
#      labels:
#        app: title
#    spec:
#      containers:
#        - name: title
#          image: nginx
#          imagePullPolicy: IfNotPresent
#          ports:
#            - containerPort: 80
#              protocol: TCP
#      restartPolicy: Always
#