apiVersion: v1
kind: Service
metadata:
  name: {{ include "coffeequeue.appName" . }}
  labels:
    {{- include "coffeequeue.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  selector:
    {{- include "coffeequeue.appSelectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.targetPort }}
  type: {{ .Values.app.service.type }}
