apiVersion: v1
kind: Service
metadata:
  name: {{ include "coffeequeue.postgresServiceName" . }}
  labels:
    {{- include "coffeequeue.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  selector:
    {{- include "coffeequeue.postgresSelectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: {{ .Values.postgres.service.port }}
  type: ClusterIP
